### PR TITLE
Fix flaky specs: Emails Budgets Selected/Unselected investment

### LINKED ISSUE #2446: Flaky spec: Emails Budgets Selected investment
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 19467

**Travis failed build:** https://travis-ci.org/consul/consul/jobs/337981250

**Failure:**

```
    1) Emails Budgets Selected investment
     Failure/Error: expect(email).to have_subject("Your investment project '#{investment.code}' has been selected")
       expected the subject to be "Your investment project '2018-26' has been selected" but was "Your investment project '2018-25' has been selected"
     # ./spec/features/emails_spec.rb:431:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### LINKED ISSUE #2519: Flaky spec: Emails Budgets Unselected investment
# What

Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 60023

**Travis failed build:** [Travis CI build 20248, job 2](https://travis-ci.org/consul/consul/jobs/349988228)

**Failure:**

```
  1) Emails Budgets Unselected investment
     Failure/Error: expect(email).to have_subject("Your investment project '#{investment.code}' has not been selected")
       expected the subject to be "Your investment project '2018-9' has not been selected" but was "Your investment project '2018-8' has not been selected"
     # ./spec/features/emails_spec.rb:454:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- [How to Deal With and Eliminate Flaky Tests - Semaphore](https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests)

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

### PR DESCRIPTION
**Pull request by javierv**
# References

* Issue #2446.
* Issue #2519.

# Objectives

Fix the flaky specs in `spec/features/emails_spec.rb:431` ("Emails Budgets Selected investment") and `spec/features/emails_spec.rb:454` ("Emails Budgets Unselected investment").

## Explain why the test is flaky, or under which conditions/scenario it fails randomly

The code in both specs is similar, so here's one of them (unnecessary lines omitted):

```ruby
investment1 = create(:budget_investment, :selected,   author: author1, budget: budget)
investment2 = create(:budget_investment, :selected,   author: author2, budget: budget)
# ...
budget.email_selected
# ...
email = open_last_email
investment = investment2
expect(email).to have_subject("Your investment project '#{investment.code}' has been selected")
```
The test assumes the last email sent will be the one addressed to the author of the last investment created. However, this isn't always the case. The code in `budget.email_selected` is:
```ruby
def email_selected
  investments.selected.each do
  # ...
```
And this code doesn't always return the selected investments in the order they were created, since postgresql by default doesn't guarantee in which order the records will be returned.

## Explain why your PR fixes it
By ordering the selected investments by ID, we ensure the last email is sent to the author of the last created investment, as the specs assume.

Notes
===================
* The implementation can probably be improved; suggestions are welcomed. IMHO the important thing is knowing these tests were failing because `open_last_email` doesn't always return the email for the last created investment.

### CODE REVIEW

File: app/models/budget.rb [hunk 1]
```diff
@@ -152,13 +152,13 @@ def investments_orders
   end
 
   def email_selected
-    investments.selected.each do |investment|
+    investments.selected.order(:id).each do |investment|
```
Comment (javierv) [inline app/models/budget.rb]: The commit message says:

> Ordering by id is certainly not very elegant; however, ordering by
another field like `created_at` is dangerous because the record could be
created at (almost) the exact same time.

However, `created_at` stores the time up to microseconds, so the chance of two records being created at the exact same time is zero.

**Comment by voodoorai2000** [comment]
Great! 👌
Thanks @javierv!
