### PR TITLE
Don't send newsletters to unconfirmed accounts

### LINKED ISSUE #3761: Consul sends newsletters to unconfirmed accounts
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

I checked the logs of my e-mail server and one of the bounces is due to an incorrect e-mail address (it ends with "@vmail.com" instead of "@gmail.com". What happened is the person created a first account with a typo in the e-mail, never got the confirmation mail and then created a new one with the correct e-mail.

### Current Behavior
[comment]: # (Describe what actually happened.)

To my surprise, sending a newsletter to all the users of the platform also sends it to this incorrect address (hence the bounce).

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Mails should never be sent to users that haven't even confirmed their e-mail address. It's creating bounces, ineffective and even if the address was correct, someone who didn't bother to finish creating their account probably doesn't want to be bothered by e-mails later on.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

- Sign up but don't confirm your account.
- Send a newsletter to all users as an admin.
- You should receive an e-mail to your unconfirmed address.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Unconfirmed accounts don't receive anything
- Check for other places where unconfirmed users might be included when they shouldn't.

### PR DESCRIPTION
**Pull request by mohsinkhansymc**
## References

* Closes #3761 

## Objectives

Prior to this PR, an unconfirmed user was considered as active. After this change a user who has confirmed his account is an active user.

### CODE REVIEW

**Comment by mohsinkhansymc** [comment]
@PierreMesure Please review, thanks

**Comment by javierm** [comment]
@mohsinkhansymc Thanks for this pull request! :smile: I'll have a look at it, hopefully next week.

In the meantime, could you add a test for the scenario we're trying to fix (sending newsletters to unconfirmed account)? :pray: Thanks!

**Comment by PierreMesure** [comment]
Thanks a lot!

Did you do any manual test? Because by looking at the other scopes like:
```
scope :newsletter,     -> { where(newsletter: true) }
scope :email_digest,   -> { where(email_digest: true) }
```
It doesn't seem like they filter by active user. Shouldn't we add that criterium to all the scopes (except `erased`)?

**Comment by mohsinkhansymc** [comment]
@PierreMesure The active check is enough as first all the users are fetched and then 

> Thanks a lot!
> 
> Did you do any manual test? Because by looking at the other scopes like:
> 
> ```
> scope :newsletter,     -> { where(newsletter: true) }
> scope :email_digest,   -> { where(email_digest: true) }
> ```
> 
> It doesn't seem like they filter by active user, but booleans like `newsletter` or `email_digest` are already set to true before the account is confirmed. Shouldn't we add that criterium to all the scopes (except `erased`)?
> 
> I will have time to try it myself on Friday.

This code should work if the said scope sends to all users, but sure you can have a look on Friday

**Comment by mohsinkhansymc** [comment]
@javierm Please review the test case, thanks

**Comment by PierreMesure** [comment]
Ah, thanks! That answers my question!

@mohsinkhansymc your test looks great. I'd say you don't need to test that `user3` is not in the array since you already tested that the array is exactly `[user1, user2]`.

File: app/models/user.rb [hunk 1]
```diff
@@ -67,7 +67,7 @@ class User < ApplicationRecord
     where(document_type: document_type, document_number: document_number)
   end
   scope :email_digest,   -> { where(email_digest: true) }
-  scope :active,         -> { where(erased_at: nil) }
+  scope :active,         -> { where(erased_at: nil).where.not(confirmed_at: nil) }
```
Comment (javierm) [inline app/models/user.rb]: Changing the `active` scope might have some side effects :thinking:. For instance, this scope is used while verifying users. What do you think about changing the `UserSegments.all_users` method instead, which will only affect newsletters?

File: spec/models/user_spec.rb [hunk 2]
```diff
@@ -399,6 +399,15 @@
         expect(User.active).not_to include(user3)
       end
 
+      it "returns users who have confirmed their account" do
```
Comment (javierm) [inline spec/models/user_spec.rb]: Since we're trying to test that newsletters aren't sent to unconfirmed accounts, how about adding a test for `Newsletter#list_of_recipient_emails` instead? https://github.com/consul/consul/blob/master/spec/models/newsletter_spec.rb#L50

File: app/models/user.rb (hunk 1 above)
Comment (mohsinkhansymc) [reply app/models/user.rb]: @javierm You are right about this, we don't know what might break. I will revert and do the change to all_users method

**Comment by mohsinkhansymc** [comment]
@javierm I have done the changes you proposed. Thanks

File: lib/user_segments.rb [hunk 3]
```diff
@@ -10,7 +10,7 @@ class UserSegments
                 not_supported_on_current_budget]
 
   def self.all_users
-    User.active
+    User.where(erased_at: nil).where.not(confirmed_at: nil)
```
Comment (javierm) [inline lib/user_segments.rb]: Maybe we can keep using the `active` scope :thinking:.
```suggestion
    User.active.where.not(confirmed_at: nil)
```

Comment (mohsinkhansymc) [reply lib/user_segments.rb]: @javierm makes sense as if the condition for active users changes in future, this will work flawlessly :+1:

**Comment by PierreMesure** [comment]
Before we close this, I'd like to point out that `User.active` is also used to calculate the number of users shown in the Statistics page on the admin panel. Is this what we want? Or do we want to reflect the number of users who actually confirmed their e-mail address?

Capture d’écran 2019-10-23 à 19 36 56

**Comment by javierm** [comment]
> In general, shouldn't we replace all the occurrences of `User.active` by a new scope that dismisses the users that didn't confirm their e-mail addresses?

The `active` scope is used in several places related to verification, which is a part of the application most forks change, so I'd rather be conservative here and keep the existing behavior :thinking:.

Regarding the admin statistics, I don't have a strong opinion; I guess both approaches are valid :thinking:.

**Comment by PierreMesure** [comment]
Yes, I agree with you that touching `active` is not a good idea. But creating a `confirmed_users` scope which we can then use in [all the places](https://github.com/consul/consul/search?p=2&q=%22User.active%22&unscoped_q=%22User.active%22) where `active` is used today?

**Comment by mohsinkhansymc** [comment]
@PierreMesure we can have a separate label on the stats page that shows confirmed accounts or we can modify the total users label to `confirmedcount/totalusers`. Also instead of showing unverified users we can show active users that will return the confirmed accounts count. What do you guys think? @javierm

**Comment by javierm** [comment]
This is an interesting topic :thinking:. Since we're trying to get everything ready for version 1.1, I'd rather be conservative and only change the code affecting newsletters. Feel free to open a new issue and continue this conversation once we release version 1.1, and maybe then we can study the implications of chaging the `active` scope.

@mohsinkhansymc For now, it would be awesome if we kept this pull request as it is, except for the [suggested change in the all_users method](https://github.com/consul/consul/pull/3781/files#r337603211), and then we can merge it and it will be included in version 1.1 :tada:.

**Comment by javierm** [comment]
@mohsinkhansymc Thanks a lot! :smile:
