### PR TITLE
Show valuator group investments to group valuators

### LINKED ISSUE #4860: Group of evaluators doesn't work as expected
### Description

It's possible to group valuators to make it faster to assign investment projects to several valuators at the same time. The problem is that the investments assigned to a valuators group don't appear in the Valuation interface.

### Steps to reproduce
1. Create a new valuator group from https://demo.consulproject.org/admin/valuator_groups.
2. Add a new Valuator and include him inside the group https://demo.consulproject.org/admin/valuators/.
3. Change the Budget phase to "Valuating projects" https://demo.consulproject.org/admin/budgets/1/edit.
4. Assign any investment to the new valuator group https://demo.consulproject.org/admin/budgets/1/budget_investments/19/edit#classification.
5. Mark "Show to valuators" checkbox from admin https://demo.consulproject.org/admin/budgets/1/budget_investments.
6. Visit Valuation interface https://demo.consulproject.org/valuation and nothing appears.

### Definition of Done

The valuation interface should display all the investments that have been assigned to the evaluator individually, as well as those assigned to all the groups to which the evaluator belongs.

### PR DESCRIPTION
**Pull request by javierm**
## References

* Closes #4860
* Depends on #5078

## Objectives

* Display the investments assigned to a valuator's group in the list of investments assigned to a valuator

### CODE REVIEW

File: spec/models/budget/investment_spec.rb [hunk 1]
```diff
@@ -414,6 +414,47 @@
...
+    end
+
+    it "does not return investments assigned to other valuators" do
+      create(:budget_investment, :visible_to_valuators, valuators: [create(:valuator)])
+
+      expect(Budget::Investment.visible_to_valuator(valuator)).to be_empty
+    end
+
+    it "does not return duplicate investments when they're assigned more than once" do
+      investment = create(:budget_investment, :visible_to_valuators)
```
Comment (Senen) [inline spec/models/budget/investment_spec.rb:433]:
```suggestion
      valuator_group = create(:valuator_group, valuators: [valuator])
      investment = create(:budget_investment, :visible_to_valuators, valuator_groups: [valuator_group])
```

With this change, we will also cover the valuator assignment through a group, or we can also a test for this scenario:

```
    it "does not return duplicate investments when valuator is directly assigned and belongs to the group" do
      valuator_group = create(:valuator_group, valuators: [valuator])
      investment = create(:budget_investment, :visible_to_valuators, valuators: [valuator],
                                                                     valuator_groups: [valuator_group])

      expect(Budget::Investment.visible_to_valuator(valuator)).to eq [investment]
    end
```

Comment (javierm) [reply spec/models/budget/investment_spec.rb:433]: @Senen I've added the test. Thanks! :smile:

**Review by Senen — APPROVED** [review]
