### PR TITLE
Sanitize values before sending them to remote translation client

### LINKED ISSUE #3872: Remote translations from other languages not working as expected.
Type: Bug

Remote translations from other languages not working as expected for ex: Greek to English.

Current behavior
Whenever we tried Remote translate/Microsoft Translations from Greek to English, we get unexpected text. We tried manually translating the same text using Microsoft Translator which worked. We get the below text when tried to translate 

> Οι αρχαίοι Έλληνες προσπάθησαν να εξηγήσουν όλα τα φυσικά φαινόμενα με μύθους. Παρακάτω είναι η εξήγησή τους για την δημιουργία του κόσμου.

  Στην αρχή υπήρχε το χάος (chaos), ένα άδειο διάστημα. Από το χάος γεννήθηκαν η Γη (earth), η νύχτα (night) και η μέρα (day). Από την Γη γεννήθηκαν τα βουνά, η θάλασσα, και ο Ουρανός (sky-Uranus), ο πρώτος θεός.   Από τον Ουρανό και την Γη γεννήθηκαν 13 παιδιά, οι τιτάνες (titans). Ο Ουρανός φοβόταν πως μια μέρα, ένα από τα παιδιά του θα του πάρει τον θρόνο.   Κάθε ένα από τα παιδιά του, μόλις γεννιόταν, ο Ουρανός, τα έριχνε σε μια βαθιά σπηλιά. Ένα από τα παιδιά του ο Κρόνος (Saturn), ο νεώτερος, ήταν πολύ έξυπνος και αποφασιστικός. Δραπέτευσε και με την βοήθεια της μητέρας του πήρε τον θρόνο από τον Ουρανό. Μετά ελευθέρωσε τους αδελφούς του και τις αδελφές του και με την βοήθειά τους έγινε ο κυρίαρχος του κόσμου.

> Ο ι α ρ χ α the ο ι a λ λ, η, ν, ε ς π ρ ο σ π, θ η σ α ν ν α ε ξ η γ σ ο υ ν λ α τ α φ υ σ. Π α ρ α κ τ ω ε i ν α ι η ε ξ, γ η, σ, τ ο υ ς γ ι α τ η ν δ η μ ι ο υ ρ γ α τ.  Σ τ η ν α ρ χ or υ π or ρ χ ε τ ο χ a ο ς (Chaos), E ν α a δ ε ι ο δ ι σ τ η μ α. Α π τ ο χ ο ς, γ ε ν, ν θ η κ α ν η (Night) Γ η (Earth η ν χ (day) τ. Α π τ η ν Γ η γ ε ν ν or θ η κ Uranus α ν τ α β ο υ ν, η θ, λ α σ σ, α κ α ι ο Ο υ, ρ. < br/h α   Α π τ ο ν Ο υ ρ α ν, κ α the ι τ η ν Γ η γ ε ν ν, θ, η Titans κ α ν π α ι. Ο Ο υ ρ α ν the ς φ a ο β the τ α of ν π ω ς μ ι α μ ρ α ν, α α π τ α π α ι δ ι τ ο υ to the θ, α.   Κ θ ε e ν α α π the τ α the π α ι δ ι a τ ο, υ, μ λ ι ς γ ε ν ν ι the τ α, ν ο Ο υ ρ α ν ς τ α ρ ι χ ν a ε σ ε μ ι α β α, θ a ι to the σ π, η the λ ι. ν τ ο υ ο Κ ρ the ν ο (Saturn), ς ο ν i ε τ, ε, ρ, or ο ς τ α ν π, ο λ ξ υ π ν ο ς κ α ι α π ο φ α σ ι. Δ ρ α π, τ ε υ, σ ε κ α ι μ ε τ η ν β ο, θ ε ι α τ η ς μ η τ ρ α ς τ ο υ π ρ ε the τ ο ν θ ρ ν, ο α π τ ο ν Ο υ ρ α ν τ ο υ ς α δ ε λ φ ο a ς τ ο υ κ α ι τ ι ς α δ ε λ φ ς τ ο υ κ α ι μ ε τ η ν β ο θ ε ι τ ο υ ς κ σ μ ο υ.

Steps to reproduce
After enabling Remote Translations in the backend. Try creating a proposal in Greek using the above Greek text then switch the language to English. You will see the above output.

Expected Behavior
The remote translations should work regardless of the original source language. 

Definition of Done
If I am able to use Remote Translation feature to reflect the proper translations regardless of original source of the language.
microsoft_translator
remote_translations

### PR DESCRIPTION
**Pull request by taitus**
## References

* Closes #3872 
* Related PR's: #3749

## Objectives
Sanitize resource fields values from ddbb before send to remote translate client.

## Visual Changes
None

## Notes
Before we saved the sanitized values in database
In #3749  was removed sanitize before saving in database and is only managed in the views.
The remote translation feature has been affected by this change, as we send the database value directly to the remote translation client. The solution is to sanitize the values of the fields before sending them to the remote translation client.

### CODE REVIEW

File: lib/remote_translations/caller.rb [hunk 1]
```diff
@@ -40,7 +42,7 @@ def translations
 
     def fields_values
       resource.translated_attribute_names.map do |field|
-        resource.send(field)
+        sanitize(resource.send(field))
```
Comment (javierm) [inline lib/remote_translations/caller.rb]: In order to keep the behaviour we had before commit 7bf4e4d6, I think we need to use `WYSIWYGSanitizer.new.sanitize` :thinking:. Then we can remove the line saying `include ActionView::Helpers::SanitizeHelper`. Correct me if I'm wrong! :wink:

File: spec/lib/remote_translations/caller_spec.rb [hunk 2]
```diff
@@ -206,4 +207,22 @@
...
+  describe "#field values" do
+    let!(:proposal)          { create(:proposal, description: "&Sigma; with sample text") }
+    let(:remote_translation) do
+      create(:remote_translation, remote_translatable: proposal, locale: :es)
+    end
+    let(:caller) { RemoteTranslations::Caller.new(remote_translation) }
+
+    it "sanitize field value when the field contains entity references as &Sigma;" do
+      field_values_sanitized = [proposal.title, "Σ with sample text", proposal.summary, proposal.retired_reason]
+      locale = remote_translation.locale
```
Comment (javierm) [inline spec/lib/remote_translations/caller_spec.rb]: It looks like this line is not necessary :thinking:.

I highly recommend configuring your editor so it runs `ruby -cw` when you save a Ruby file and tells you about errors and warnings reported by the Ruby interpreter (not to be confused with rubocop, which has many more rules and is much slower). For example, with Vim this is automatically done when installing syntastic.

[the remark this answers is not in the document]
Comment (taitus) [reply spec/lib/remote_translations/caller_spec.rb]: This variable is now used!
